### ISSUE TITLE
capsolver is not working

### ISSUE THREAD

**Issue by stclouds** [omkarcloud/outlook-account-generator#27] opened 2023-12-13 17:46 UTC
Hi. capsolver is not working.Can you help me please. 

```
Traceback (most recent call last):
  File "C:\Users\Windows\Desktop\bot\hotmail\outlook-account-generator-master\src\outlook\create_accounts_utils.py", line 316, in solvecaptcha_with_captcha_solver
    token = solve_captcha("B7D8911C-5CC8-A9A3-35B0-554ACEE604DA",  "https://signup.live.com/?lic=1", "https://client-api.arkoselabs.com",blob, getua(driver), proxy, capsolver_apikey)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\Desktop\bot\hotmail\outlook-account-generator-master\src\outlook\solve_captcha.py", line 17, in solve_captcha
    solution = capsolver.solve(data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\capsolver\capsolver.py", line 37, in solve
    r = cls.postTask(params)
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\capsolver\capsolver.py", line 18, in postTask
    return cls().request("post", "/createTask", {"task":params})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\capsolver\capsolver_object.py", line 59, in request
    return requestor.request(method, url, params=params, headers=headers, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\capsolver\api_requestor.py", line 57, in request
    result = self.request_raw(method.lower(), url, params=params, supplied_headers=headers, request_timeout=request_timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\capsolver\api_requestor.py", line 127, in request_raw
    raise error.APIError("Error communicating with capsolver") from e
capsolver.error.APIError: APIError: Error communicating with capsolver

```

**Comment by CafePromenade** [comment] 2023-12-13 17:47
Having a similar issue




 Traceback (most recent call last):
  File "C:\Users\School\Downloads\outlook-account-generator-master\src\outlook\create_accounts_utils.py", line 316, in solvecaptcha_with_captcha_solver
    token = solve_captcha("B7D8911C-5CC8-A9A3-35B0-554ACEE604DA",  "https://signup.live.com/?lic=1", "https://client-api.arkoselabs.com",blob, getua(driver), proxy, capsolver_apikey)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\School\Downloads\outlook-account-generator-master\src\outlook\solve_captcha.py", line 18, in solve_captcha
    solution = capsolver.solve(data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\capsolver\capsolver.py", line 39, in solve
    raise r
capsolver.error.InvalidRequestError: InvalidRequestError: invalid task data: The current website is under maintenance, please try again later.
Skipping Account Creation due to Detection.
The Bot has been detected. To create more accounts, kindly change your IP and press Enter to continue...

**Comment by diegoooooooooooooooo** [comment] 2023-12-15 17:08
Hello,

Thank you for bringing this issue to our attention. I've investigated the error and found that the captcha solver was not receiving the correct URL due to a misconfiguration. To address this, I've made the necessary changes and submitted a pull request to the original repository of the project.

You can find the pull request here for a detailed view of the changes: [PR #31 on omkarcloud/outlook-account-generator](https://github.com/omkarcloud/outlook-account-generator/pull/31).

This pull request includes the fix for the incorrect URL that was previously being used in the captcha resolution process. Once the pull request is merged by the project owner, the solution should work as intended.

In the meantime, if you're familiar with Git, you can manually merge these changes into your local copy of the project to get around the issue.

Let me know if you need further assistance!

**Comment by Chetan11-dev** [comment] 2023-12-24 05:55
I am closing this issue. Finally, if Capsolver does not fix Funcaptcha by January 3rd, I will attempt to implement an alternative captcha solver, such as 2Captcha or AnyCaptcha.

**Closed by Chetan11-dev** 2023-12-24 05:55 UTC
